[package]
name = "pacgate-workflow"
version.workspace = true
edition.workspace = true

[dependencies]
pacgate-core = { path = "../pacgate-core" }
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sqlx.workspace = true
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true
chrono.workspace = true
